test/app.spec.js, test/child-router.spec.js, test/flickr.spec.js
simple tests for router configuration, activation, and deactivation
=> tests(skeleton): add tests for app, child router, and flickr

gulpfile.js
Allows the dev to git clone and build all projects
=> feat(tools): Added build-dev-env task to skeleton-navigation

protractor.conf.js, test/e2e/dist/demo.spec.js, test/e2e/dist/skeleton.po.js, test/e2e/dist/welcome.po.js, test/e2e/src/demo.spec.js, test/e2e/src/skeleton.po.js, test/e2e/src/welcome.po.js
feat(e2e): add protractor locator and e2e PO test
Adds a custom protractor locator valueBind as well as better E2E tests
using the Page Object Pattern.
=> feat(e2e): add protractor locator and e2e PO test

test/e2e/dist/demo.spec.js, test/e2e/dist/welcome.po.js, test/e2e/src/demo.spec.js, test/e2e/src/welcome.po.js
test(e2e): fixed E2E tests
Fixes the alert bug for win and mac. Adds all tests back to action. Adds
a browser.sleep plus comments for reason
=> test(e2e): fixed E2E tests

aurelia.protractor.js, config.js, package.json, protractor.conf.js, test/e2e/dist/demo.spec.js, test/e2e/dist/skeleton.po.js, test/e2e/dist/welcome.po.js, test/e2e/src/demo.spec.js, test/e2e/src/skeleton.po.js
feat(e2e): add protractor plugin, add waitMethods
A customer protractor aurelia plugin, used to exclude specific
configuration out of the protractor.conf file. Additional wait methods
for Aurelia Events attached to global browser object.
=> feat(e2e): add protractor plugin, add waitMethods

build/tasks/test.js
Just the tasks and nothing else.
=> Added Karma gulp tasks

config.js, package.json
rebuilt config.js to make jspm download 0.8.8 version of templating-resources. Package.json file got updated by jspm. Let me know if you want me to remove it from the PR.
=> chore(jspm): rebuild config.js

test/unit/app.spec.js, test/unit/child-router.spec.js
Fixes updated app/childrouter routes in the unit tests
=> fix(tests): Update routes in unit tests

README.md
Adds more information on how to properly run E2E tests
=> fix(readme): More info about E2E workflow

config.js, index.html, package.json, src/animation-main.js, src/child-router.html, src/flickr.html, src/welcome.html, src/welcome.js, styles/styles.css
This adds example animations for page transitions, validations and repeated lists
Please take a look at the config.js and package.json files, have the feeling that something got messed up there
=> feat(anim): Add animation example

index.html
Add the viewport meta tag to ensure proper rendering and touch zooming.
=> fix(index): add the viewport meta tag

package.json
=> Reinstate proper css JSPM dependency

test/unit/app.spec.js, test/unit/child-router.spec.js
Fixes the unit tests for the app- and child-router
Fixes  issue https://github.com/aurelia/skeleton-navigation/issues/87
=> fix(tests): Fix unit tests for new release

src/flickr.html, styles/styles.css
This adds staggering animations to the flickr gallery example
=> feat(anim): adds staggering animations

test/unit/app.spec.js, test/unit/child-router.spec.js
Added the flickr title to the route in the tests as well
Fixes issue https://github.com/aurelia/skeleton-navigation/issues/96
=> fix(karma): Fixed tests to adhere to new flickr route

test/unit/app.spec.js, test/unit/child-router.spec.js
add router name for the app- and child-router
for this commit: https://github.com/aurelia/skeleton-navigation/commit/a3cb19ce63f9a53c58c36244f9cca20ead54fb32
=> fix(tests): Fix unit tests

config.js
=> chore(config): remove extra fetch in config.js

build/tasks/dev.js, build/tasks/e2e.js, build/tasks/prepare-release.js, build/tasks/watch.js, src/app.js, src/blur-image.js, src/child-router.js, src/users.js, src/welcome.js, styles/styles.css, test/unit/app.spec.js, test/unit/child-router.spec.js
This is request contains smaller cleanups and linting.
=> Code Cleanup

package.json, wallaby.js
Added wallaby.js runner configuration.
=> Wallaby.js configuration

README.md
Info that the skeleton is using BrowserSync and how to turn of the ghostMode option
=> docs(browsersync): info about browsersync

protractor.conf.js
fixes the path to the e2e tests
fixes issue https://github.com/aurelia/skeleton-navigation/issues/180
=> fix(protractor): fix e2e tests path

LICENSE, package.json
See #56 for reasoning.
Copied verbatim from http://creativecommons.org/publicdomain/zero/1.0/legalcode.txt.
HTML version with links to other languages and FAQ: http://creativecommons.org/publicdomain/zero/1.0/legalcode
=> Changes license to CC0.

src/welcome.js
=> Fixed typo

README.md, build/paths.js, build/tasks/bundle.js, build/tasks/export-release.js, bundles.json, export.json
external bundles.json for bundle configuration 
new "export" gulp task - export app for servers preserving directory structure
updated README for usage
=> bundles.json for bundle configuration and export gulp task

build/export.json
Closes aurelia/skeleton-navigation#213
=> Updated fetch polyfill version in export task so export works

build/tasks/watch.js
=> fix(build): do not reload after CSS injection

build/tasks/dev.js
Add `pull-dev-env` gulp task to support changes made in aurelia/tools#26
=> feat(build): add pull-dev-env task

karma.conf.js
This fixes aurelia/skeleton-navigation#235
=> Do not append an extra .js extension for karma

skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/.gitignore, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/args.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/bundles.json, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/export.json, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/paths.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/build.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/bundle.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/clean.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/dev.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/e2e.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/export-release.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/lint.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/prepare-release.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/test.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/watch.js
Removing them from .gitignore as well
=> fix(build): add build tasks back in

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/package.json, skeleton-es2016/package.json, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/package.json, skeleton-typescript/package.json
=> fix(artifact): remove istanbul artifacts

skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/package.json, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/wwwroot/config.js, skeleton-typescript/config.js
Fixes #294.
Follows 45111bd77eb551051a16c395d093156aaef95725.
=> chore(typescript): remove babel transpiler

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/karma.conf.js, skeleton-es2016/karma.conf.js
this is better [karma-jspm](https://www.npmjs.com/package/karma-jspm) configuration
=> load only test javascript to browser, but serve all source files

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/README.md, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/bundles.js, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/export.js, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/tasks/bundle.js, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/tasks/export-release.js, skeleton-es2016/README.md, skeleton-es2016/build/bundles.js, skeleton-es2016/build/export.js, skeleton-es2016/build/tasks/bundle.js, skeleton-es2016/build/tasks/export-release.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/README.md, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/bundles.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/export.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/bundle.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/export-release.js, skeleton-typescript/README.md, skeleton-typescript/build/bundles.js, skeleton-typescript/build/export.js, skeleton-typescript/build/tasks/bundle.js, skeleton-typescript/build/tasks/export-release.js
=> change bundles.json and export.json to javascript format

skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/wallaby.js
Updates to match other wallaby.js files
=> chore(tests): update wallaby.js config ts asp.net5

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/karma.conf.js, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/test/unit/app.spec.js, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/test/unit/child-router.spec.js, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/test/unit/users.spec.js, skeleton-es2016/karma.conf.js, skeleton-es2016/test/unit/app.spec.js, skeleton-es2016/test/unit/child-router.spec.js, skeleton-es2016/test/unit/users.spec.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/karma.conf.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/test/unit/app.spec.ts, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/test/unit/child-router.spec.ts, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/test/unit/users.spec.ts, skeleton-typescript/karma.conf.js, skeleton-typescript/test/unit/app.spec.ts, skeleton-typescript/test/unit/child-router.spec.ts, skeleton-typescript/test/unit/users.spec.ts
i loaded the setup from karma.conf.js, which worked just fine. seems easier that way (loadFiles are loaded in order)
=> chore(test): moved setup.js loading to karma.conf.js

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/wallaby.js, skeleton-es2016/wallaby.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/wallaby.js, skeleton-typescript/wallaby.js
Added the newly added `test/unit/setup.js`/`test/unit/setup.ts` file to the `files` list (fixes [#495](https://github.com/wallabyjs/public/issues/495))
=> chore(tests): update wallaby.js config files

skeleton-typescript/karma.conf.js
Similar to PR #334 for wallaby.js, fixes null error during test run.
=> chore(tests): update karma config file

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/project.json, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/project.json
Removes some artifacts from project.json
Fixes #345
=> chore(project.json): remove artifacts

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/package.json, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/wwwroot/config.js, skeleton-es2016/config.js, skeleton-es2016/package.json
Since transpiling is done by gulp it is not needed in the browser.
=> chore(jspm): disable in-browser transpiler

README.md, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/README.md, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/tasks/build.js, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/gulpfile.js, skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/package.json, skeleton-es2016-webpack/README.md, skeleton-es2016-webpack/package.json, skeleton-es2016-webpack/protractor.conf.js, skeleton-es2016/README.md, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/README.md, skeleton-typescript/README.md
When using Gulp with Visual Studio, projects will sometimes not run if there is an issue with one of the dependencies. This PR updates the `gulp-eslint` and `run-sequence` dependencies so that the project compiles.
I also added the `gulp-jspm` task so that `jspm install` can be run by Visual Studio without having to open a command prompt. Finally, I updated gulpfile.js so Visual Studio automatically runs the `clean`, `gulp-system`, `gulp-html`, `gulp-css`, and `gulp-jspm` tasks when the project is built.
=> Updated ASP.NET ES2016 skeleton

skeleton-es2016-webpack/package.json, skeleton-es2016-webpack/src/main.js, skeleton-es2016-webpack/webpack.config.js, skeleton-es2016-webpack/webpack.prod.config.js
add bootstrap.js and jquery.js as dependencies, load bootstrp.js
in main.js.
closes: #385
=> fix(webpack): main menu not working in mobile

skeleton-es2016-webpack/README.md, skeleton-typescript-webpack/README.md
Added a note about the aurela-webpack-plugin's config in the skeletons' README's.
aurelia/dialog#132
=> Added a note on the webpack-plugin's config in the skeletons' readmes

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/wwwroot/config.js, skeleton-es2016/config.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/wwwroot/config.js, skeleton-typescript/config.js
- remove duplicate jquery versions
- fix aurelia/bundler#92
The typescript and vs versions are untested, because I have no clue of it.
=> chore(jspm): update bootstrap's jquery deps

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/karma.conf.js, skeleton-es2016/karma.conf.js, skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/karma.conf.js, skeleton-typescript/karma.conf.js
Enables component testing using aurelia-testing.
=> fix(karma.config.js): serve everything in src

skeleton-es2016/index.js, skeleton-typescript/index.html, skeleton-typescript/index.js
Electron app initialization seems to have changed. See [electron-quick-start/main.js](https://github.com/electron/electron-quick-start/blob/master/main.js)
=> Fix electron initialization

skeleton-es2016/README.md, skeleton-es2016/build/tasks/serve.js, skeleton-es2016/config.js, skeleton-es2016/index.html, skeleton-es2016/package.json, skeleton-typescript/README.md, skeleton-typescript/build/export.js, skeleton-typescript/build/tasks/build.js, skeleton-typescript/build/tasks/export-release.js, skeleton-typescript/build/tasks/serve.js, skeleton-typescript/config.js, skeleton-typescript/index.html, skeleton-typescript/package.json
* update some dependencies
* synced tasks
* add task `serve-export`
=> Jspm skeleton sync

skeleton-typescript/build/bundles.js
closes https://github.com/aurelia/skeleton-navigation/issues/487
=> fix(skeleton-typescript):  bundle fetch

skeleton-esnext-aspnetcore/src/skeleton/README.md, skeleton-typescript-aspnetcore/src/skeleton/README.md
Please let me know if these updates are satisfactory
=> doc(aspnetcore): update readme files

skeleton-esnext-aspnetcore/src/skeleton/build/tasks/export-release.js, skeleton-esnext/build/tasks/export-release.js, skeleton-typescript-aspnetcore/src/skeleton/build/tasks/export-release.js, skeleton-typescript/build/tasks/export-release.js
Add this back so that this will work on Node 4.x.
=> chore(export): add "use strict" to export-release

ISSUE_TEMPLATE.md
=> chore(issue_template): create issue template

ISSUE_TEMPLATE.md
Some minor tweaks to the formatting to make it display better. The rendered markdown is included below:
**I'm submitting a bug report**
**I'm submitting a feature request**
* **Aurelia Skeleton Version**
skeleton-esnext
skeleton-esnext-aspnetcore
skeleton-esnext-webpack
skeleton-typescript
skeleton-typescript-aspnetcore
skeleton-typescript-webpack
* **aurelia-framework version:**
1.0.0-rc.1.0.2
**Please tell us about your environment:**
* **Operating System:**
OSX 10.x|Linux (distro)|Windows [7|8|8.1|10]
* **Node Version:**
6.2.0
* **NPM Version:**
3.8.9
* **JSPM OR Webpack AND Version**
JSPM 0.16.32 | webpack 2.1.0-beta.17
* **Browser:**
all | Chrome XX | Firefox XX | Edge XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX …
=> chore(issue_template): update formatting

skeleton-esnext-aspnetcore/src/skeleton/package.json, skeleton-esnext/package.json
It's the latest and greatest!!!
=> chore(eslint): update to latest version of eslint

skeleton-typescript/tsconfig.json
=> chore(lint): fix test linting

skeleton-typescript-aspnetcore/src/skeleton/karma.conf.js
=> Fixed serveFiles Karma attribute

skeleton-esnext-aspnetcore/src/skeleton/views/home/Index.cshtml, skeleton-esnext/index.html, skeleton-typescript-aspnetcore/src/skeleton/views/home/Index.cshtml, skeleton-typescript/index.html
Moves Bluebird script after SystemJS.
=> fixes #716

skeleton-typescript-aspnetcore/src/skeleton/build/tasks/test.js, skeleton-typescript/build/tasks/test.js
=> chore(ts-tests): clean before tests

skeleton-esnext-aspnetcore/src/skeleton/package.json, skeleton-typescript-aspnetcore/src/skeleton/package.json
=> chore(aspnetcore): fix windows install issues

skeleton-typescript-aspnetcore/src/skeleton/tsconfig.json, skeleton-typescript-webpack/tsconfig.json, skeleton-typescript/tsconfig.json
=> fix(typescript-webpack): TypeScript should not auto-compile to .js file

skeleton-esnext-webpack/package.json, skeleton-typescript-webpack/package.json
=> fix aurelia- being stripped from module name

skeleton-typescript-aspnetcore/src/skeleton/karma.conf.js, skeleton-typescript-aspnetcore/src/skeleton/package.json, skeleton-typescript/karma.conf.js, skeleton-typescript/package.json
=> Fix karma/jspm to handle typescript > 2.3.1
