build/paths.js
build/tasks/build.js

This is based on conversations had yesterday in the gitter channel.

fix(build): use relative path for source maps. resolve #66

---

src/nav-bar.html

When the screen size is small, like on a mobile phone, the navbar will collapse the menu items into an expandable hamburger menu. Clicking a menu item inside of the expanded menu should automatically collapse the menu. This change will auto collapse the expanded menu when the user clicks on a menu item. This way, the user does not have to go close the menu that is blocking their view.

fix(navbar): automatically collapse the navigation menu on click

---

config.js
index.html
karma.conf.js
package.json

This removes the need for the index.html jspm.path.* override and sets up the proper pathing for the test environment inside karma.conf
Fixes issue https://github.com/aurelia/skeleton-navigation/issues/55

fix(karma): properly set jspm paths for karma

---

src/flickr.js
src/welcome.js

Move canDeactivate prompt into the Welcome view, and only trigger it when there are unsaved changes. I.e., when the name has been changed but "Submit" has not been clicked.
The prompt is a little annoying when you're just clicking around to test changes, so this prevents it from appearing on every navigation to a view.

feat(flickr): move canDeactivate prompt into Welcome

---

build/paths.js
build/tasks/build.js

This PR switches to including the original source in the source map. This is the recommended practice per the `gulp-sourcemaps` [documentation](https://www.npmjs.com/package/gulp-sourcemaps).
>Including the content is the recommended way, because it "just works". When setting this to false you have to host the source files and set the correct sourceRoot.
This should make source maps work for all situations now. I tested this with `welcome.js` located at `src\foo\welcome.js` and serving the app from `http://localhost:9000/app/` as well as from `http://localhost:9000/`. In both cases (site served from root or subfolder), `foo\welcome.js` as well all of the other ES6 files were able to be debugged.

fix(build): include source in source maps. resolve #111

---

styles/styles.css

fixes print-preview problem with Chrome due to absolute positioned element with overflows set to auto/hidden
fixes issue https://github.com/aurelia/skeleton-navigation/issues/90

fix(css): fix print styles

---

index.html

The `type` attribute on the `link` tag is optional and defaults to `text/css` when `rel="stylesheet"`. Removing the `type` attributes gives a bit cleaner HTML and shaves a few bytes of the response.
[Spec](http://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-link-type) (emphasis mine)
> The `type` attribute gives the MIME type of the linked resource. **It is purely advisory**. The value must be a valid MIME type.
[Spec](http://www.w3.org/html/wg/drafts/html/master/semantics.html#link-type-stylesheet)
> The default type for resources given by the `stylesheet` keyword is `text/css`.

refactor(index): remove type from link tags

---

aurelia.protractor.js
test/e2e/src/skeleton.po.js

We now use the event aggregator to listen for router completed events instead of a custom event from the HTTP client.

fix(test): fix e2e test broken during fetch-client migration

---

package.json

and `npm run e2e` script
resolves #147
reject this if `npm test` was intentionally left unimplemented

adds `npm test` script

---

build/tasks/serve.js

Speeds up serve, especially while offline.
http://www.browsersync.io/docs/options/#option-online

perf(serve): speed up serve task

---

README.md
package.json

JSPM recommends having a local copy of jspm in addition to the global one.
> It is advisable to locally install to lock the version of jspm. This will ensure upgrades to the global jspm will not alter the behavior of your application.
Resolves #134 "Does it make sense to install jspm locally by default?"

Declare jspm as a dependency

---

build/tasks/bundle.js
package.json

- Exclude all potential Aurelia modules from the `app-build` bundle.
- Further shorten the `module names without maps` in bundle config.
These changes now allows us to specify `aurelia/templating-binding` instead of `github:aurelia/templating-binding@0.16.0` or `github:aurelia/templating-binding` in the bundle config.

fix(bundle): shoreten the long module name in bundle config

---

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/wwwroot/css/site.css
skeleton-es2016/styles/styles.css
skeleton-typescript/styles/styles.css

this fixes an issue where animations would not work in firefox
due to the use of the !important flag.

fix(css): fixes opacity problem with FireFox

---

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/wallaby.js
skeleton-es2016/wallaby.js
skeleton-typescript/wallaby.js

Updated wallaby.js configuration files, major changes:
- fixed asp.net project file to reflect the change of moving `jspm_packages ` to `wwwroot` folder, see [#238](https://github.com/aurelia/skeleton-navigation/issues/238#issuecomment-173925883);
- added better failed promise error reporting, as described in the [wallaby docs](http://wallabyjs.com/docs/integration/jspm.html);
- removed babel dependency from the config because wallaby resolves it automatically now.

chore(tests): update wallaby.js config files

---

skeleton-es2016-webpack/index.prod.html

The webpack skeleton uses explicit bootstrapping (in src/main.js) without the aurelia-app attribute because its needs to have an entry point for webpack anyway. Forgot to remove the attribute from the prod template.

Removed aurelia-app attribute from prod template

---

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/paths.js
skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/tasks/export-release.js
skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/paths.js
skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/export-release.js

the gulp export task used the project root folder when trying to find resources from export.json. The fix changes this to instead use the wwwroot folder, so the existing export.json file works as intented.
no breaking changes I am aware of
note: this doesn't fix issue https://github.com/aurelia/skeleton-navigation/issues/284, that one should probably be a separate fix. Maybe a configuration flag whether to use bundles with rev numbers or not?
CLA signed

fix(export): use the wwwroot folder as the root for the export instead of the project root

---

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/tasks/test.js
skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/tasks/test.js

the gulp test task, when at least one unit test fails, crashes with an unhandled exception, stacktrace: at formatError (C:\...\npm\node_modules\gulp\bin\gulp.js:169:10).
Reason for failure and suggested fix explained here: https://github.com/Swiip/generator-gulp-angular/issues/498#issuecomment-102185093
After applying this fix, the gulp test task runs to completion successfully even with failed tests.
Steps to repro: Make at least one unit test fail, run gulp test
no breaking changes

fix(test): run gulp test to completion during a test run with at least one failing test

---

skeleton-es2016-webpack/package.json
skeleton-es2016-webpack/src/main.js
skeleton-es2016-webpack/webpack.config.js
skeleton-es2016-webpack/webpack.prod.config.js

Adding bluebird dependency as "Promise" polyfill for Internet Explorer 11 support. Also configured webpack ProvidePlugin so that Promise is exposed to other dependencies (as it is needed by aurelia-webpack-loader).
More info here: https://github.com/aurelia/bootstrapper-webpack/issues/3

Adding Promise polyfill to support IE11

---

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/export.js
skeleton-es2016/build/export.js
skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/export.js
skeleton-typescript/build/export.js

**Overview of the Issue** - When bundling/exporting the skeleton app, Glyphicon fonts (provided by Bootstrap) are not exported.
**Motivation or Use Case** - While font-awesome is also used, if a beginner to Aurelia tries to use Glyphicon fonts as per Bootstrap docs, they will have to investigate bundling, which can be quite complex to a beginner.
**Related Issues** - Could not find related issues

Add glyphicon font paths to export.json

---

skeleton-typescript-webpack/webpack.prod.config.js

Closes #373,by:
- fixing typo (from tsloader to ts-loader)
- adding missing `extensions: ['', '.js', '.ts']` - lack of which was blocking entry (src/main)

Fix issue #373

---

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/README.md
skeleton-es2016/README.md
skeleton-typescript/README.md

1. Corrected the electron section in readme for `skeleton-es2016` and `skeleton-typescript`
2. Removed the electron section in readme for `skeleton-es2016-asp.net5` - using electron in this environment makes no sense

chore(all): fix readme for electron case

---

skeleton-es2016-webpack/package.json
skeleton-es2016-webpack/test/unit/users.spec.js
skeleton-es2016-webpack/wallaby.js

Added a wallaby config for the webpack skeleton, this required me to import the Promise polyfill in users.spec.js to get it to run properly with wallaby.
ref issue: https://github.com/aurelia/skeleton-navigation/issues/343

wallaby config added to skeleton-es2016-webpack

---

skeleton-typescript-webpack/index.html
skeleton-typescript-webpack/webpack.config.js

Fix 'npm run build' problem. Now 'npm run dev' and 'npm run build' can be used for the same index.html.
close issue #402

fix(skeleton-typescript-webpack): edit index.html and webpack.config.js

---

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/bundles.js
skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/package.json
skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/wwwroot/config.js
skeleton-es2016-webpack/package.json
skeleton-es2016-webpack/src/main.js
skeleton-es2016/build/bundles.js
skeleton-es2016/config.js
skeleton-es2016/package.json
skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/bundles.js
skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/package.json
skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/wwwroot/config.js
skeleton-typescript-webpack/package.json
skeleton-typescript-webpack/src/main.ts
skeleton-typescript-webpack/webpack.config.js
skeleton-typescript-webpack/webpack.prod.config.js
skeleton-typescript/build/bundles.js
skeleton-typescript/config.js
skeleton-typescript/package.json

- all but vs versions tested. but it's just the same for all of them anyways
- for the webpack version, i prefer my approach
- i considered using the jquery coming with the bootstrap install, but possible ways to do that would break just too easily. an own jquery installation seems preferable 
replacing: https://github.com/aurelia/skeleton-navigation/pull/410

fix(bundle): include jquery. needed for nav-bar dropdown

---

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/package.json
skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/wallaby.js
skeleton-es2016/package.json
skeleton-es2016/wallaby.js

Looks like karma configs in these projects are using babel 6, also `skeleton-es2016-webpack` wallaby config is using babel 6, so I have updated the rest of wallaby configs use babel 6.

chore(tests): update wallaby.js config files to babel 6

---

skeleton-es2016/build/tasks/export-release.js

This fixes issue #409, where bundled javascript files with `rev: true` set on the bundle are not copied to the export directory. This solution adds a single wildcard character into the glob that ensures files with a thumbprint ID in their name are included in the export-copy task. e.g. currently this file is copied correctly:
aurelia.js
...but this file is not copied:
aurelia-c440bb4410.js
This PR adds a wildcard char to the glob that ensures both filenames would be copied to the export correctly.

Update function getBundles() in export-release.js

---

skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/build/bundles.js
skeleton-es2016/build/bundles.js
skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/build/bundles.js
skeleton-typescript/build/bundles.js

With this change, all files and subfolders of the 'src' directory are included in the app-bundle. I think that is a useful default.

chore(jspm): include src subfolders into bundle

---

skeleton-typescript-webpack/package.json
skeleton-typescript-webpack/wallaby.js

Add a wallaby.js file for skeleton-typescript-webpack.
Still has an issue with Promise not being defined when running tests with wallaby.

chore(all): add wallaby config file

---

skeleton-typescript-asp.net5/src/skeleton-navigation-typescript-vs/gulpfile.js

BeforeBuild binding for visual studio was set to 'build-html, build-css, build-jspm' instead of just using 'build'. 'build-system' was missing and so TypeScript files were not transpiled.

chore(asp.net5): fixed TypeScript transpile in Visual Studio build

---

skeleton-es2016/build/bundles.js
skeleton-es2016/build/export.js
skeleton-es2016/build/tasks/export-release.js

Changes: 
- Added fetch to the bundle. It wasn't included due to it being imported in a VM, but not in `aurelia-fetch-client`.
- Updated `export-release.js` to use ES2015 features. Added a new tasks that gets the path to any jspm package and then uses that path to copy resources from that jspm package's folder. This removes the need to keep the file list in `export.js` manually up to date.
- Modifed `export.js` to include the necessary structure for exporting `font-awesome` and its font files as well as the font files for `bootstrap`. 
I have not tested this on `node` versions below `5.10.0`, but the research I have done leads me to believe it should work as I don't believe I am using any ES2015 features that haven't been supported since Node 4.x, but I think this should be tested on the …

chore(export): normalize jspm sourced resources

---

skeleton-webpack/config/webpack.base.js

The current skeleton didn't apply the babel loader to aurelia es215 files on windows due to the path separator character.
This patch simply tests for both `\` and `/` in the include regex

Allow for sweet sweet bable lovin on Windows too

---

skeleton-esnext-aspnetcore/src/skeleton-navigation-esnext-vs/build/tasks/test.js
skeleton-esnext/build/tasks/test.js
skeleton-typescript-aspnetcore/src/skeleton-navigation-typescript-vs/build/tasks/test.js
skeleton-typescript/build/tasks/test.js

This fixed `gulp test` to return the proper error codes on test failures instead of always returning `0`.
Helpful to avoid having automated builds turn out green even when tests are failing.

fix(build): return non-zero error code on test failures

---

skeleton-typescript-aspnetcore/src/skeleton-navigation-typescript-vs/Startup.cs

Added:
```
app.UseDefaultFiles();
```
so that index.html will be served as the default document.
Removed
```
app.useMvc...
```
As Mvc routes are not being used.
Also removed:
```
services.AddMvc();
```
as MVC is not being used.

fix(skeleton_navigation_typescript_aspnetcore): comment out MVC code

---

skeleton-esnext-aspnetcore/src/skeleton/build/tasks/build.js
skeleton-esnext-aspnetcore/src/skeleton/package.json
skeleton-esnext/build/tasks/build.js
skeleton-esnext/package.json
skeleton-typescript-aspnetcore/src/skeleton/build/tasks/build.js
skeleton-typescript-aspnetcore/src/skeleton/package.json
skeleton-typescript/build/tasks/build.js
skeleton-typescript/package.json

Fixes #340 by minifying the HTML on build to prevent developers from
editing the src.

chore(build): update to minify html on build

---

skeleton-esnext-webpack/src/main.js
skeleton-typescript-webpack/src/main.ts

Not sure when this line got removed from the webpack skeletons, but without it, the navbar won't function on a narrow/mobile screen.

fix(main): load bootstrap's javascript code

---

skeleton-esnext/README.md
skeleton-typescript/README.md

Include packaging instructions using electron-packager.
Add Note that "main" in package.json needs to be changed to 'index.js' for packaging to succeed.
NOTE: this README.md update should also be applied to the skeleton-esnext README, since both appear to have the same instructions for running within Electron.

Update README.md to add packaging instructions

---

skeleton-esnext/index.html

Follow best practice to explicitly declare a charset.
Relates to #642

fix(index): specify utf-8 as the charset [esnext]

---

skeleton-esnext-webpack/index.html

Follow best practice to explicitly declare a charset.
Relates to #642

fix(index): specify utf-8 as the charset [esnext-webpack]

---

skeleton-typescript/index.html

Follow best practice to explicitly declare a charset.
Relates to #642

fix(index): specify utf-8 as the charset [typescript]

---

skeleton-typescript-webpack/index.html

Follow best practice to explicitly declare a charset.
Relates to #642

fix(index): specify utf-8 as the charset [typescript-webpack]

---

skeleton-esnext/index.js
skeleton-typescript/index.js

I'm going to file a bug with @guybedford to see if he can do something about this on the JSPM/SystemJS side. Left a link showing how to re-enable node integration, but I didn't want to muddy up `index.html` with code that was unnecessary for everyone except Electron users.  They can follow the instructions in the Electron FAQ if they want to.
Fixes #674

chore(electron): disable electron node integration to fix jquery

---

skeleton-typescript-webpack/webpack.config.js

Fixes error “Conflict: Multiple assets emit to the same filename f952101eaf243f0f36fb.chunk.js” by using chunk name in file name in Webpack config.
```
ERROR in chunk users
f952101eaf243f0f36fb.chunk.js
Conflict: Multiple assets emit to the same filename f952101eaf243f0f36fb.chunk.js
ERROR in chunk welcome
f952101eaf243f0f36fb.chunk.js
Conflict: Multiple assets emit to the same filename f952101eaf243f0f36fb.chunk.js
ERROR in chunk 3
f952101eaf243f0f36fb.chunk.js
Conflict: Multiple assets emit to the same filename f952101eaf243f0f36fb.chunk.js
```
https://github.com/jods4/aurelia-webpack-build/tree/master/demos/03-Code_splits
Using `[name].js` in Webpack config for chunkFilename to solve the above error.
Only using `[hash].js` will conflict as hash isn't unique. `[chunkhash]` on the other …

fix(code splitting): Fix error “Multiple assets emit”

---

skeleton-typescript/package.json

Current configuration not compatible with latest TypeScript.  Lock it at
2.2.1 on a known working version and update next.
Fixes #823 #281 #

chore(tests): lock version of typescript
